function Hd = BPFilterBase
%BPFILTERBASE Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.1 and the Signal Processing Toolbox 7.3.
% Generated on: 20-Feb-2019 14:04:11

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 160;  % Sampling Frequency

Fstop1 = 0;               % First Stopband Frequency
Fpass1 = 2;               % First Passband Frequency
Fpass2 = 40;%20;              % Second Passband Frequency
Fstop2 = 42;%22;              % Second Stopband Frequency
Dstop1 = 0.001;           % First Stopband Attenuation
Dpass  = 0.057501127785;  % Passband Ripple
Dstop2 = 0.001;           % Second Stopband Attenuation
dens   = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 1 ...
                          0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
